[package]
name = "bwcoreutils"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "bwcoreutils — Black Wall Core core userspace utilities"

# Each utility is its own binary.
[[bin]]
name = "ls"
path = "src/ls.rs"

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "cp"
path = "src/cp.rs"

[[bin]]
name = "mv"
path = "src/mv.rs"

[[bin]]
name = "rm"
path = "src/rm.rs"

[[bin]]
name = "mkdir"
path = "src/mkdir.rs"

[[bin]]
name = "rmdir"
path = "src/rmdir.rs"

[[bin]]
name = "touch"
path = "src/touch.rs"

[[bin]]
name = "echo"
path = "src/echo.rs"

[[bin]]
name = "pwd"
path = "src/pwd.rs"

[[bin]]
name = "hostname"
path = "src/hostname.rs"

[[bin]]
name = "uname"
path = "src/uname.rs"

[[bin]]
name = "whoami"
path = "src/whoami.rs"

[[bin]]
name = "id"
path = "src/id.rs"

[[bin]]
name = "ps"
path = "src/ps.rs"

[[bin]]
name = "kill"
path = "src/kill.rs"

[[bin]]
name = "grep"
path = "src/grep.rs"

[[bin]]
name = "find"
path = "src/find.rs"

[[bin]]
name = "head"
path = "src/head.rs"

[[bin]]
name = "tail"
path = "src/tail.rs"

[[bin]]
name = "wc"
path = "src/wc.rs"

[[bin]]
name = "df"
path = "src/df.rs"

[[bin]]
name = "du"
path = "src/du.rs"

[[bin]]
name = "date"
path = "src/date.rs"

[[bin]]
name = "sort"
path = "src/sort.rs"

[[bin]]
name = "uniq"
path = "src/uniq.rs"

[[bin]]
name = "chmod"
path = "src/chmod.rs"

[[bin]]
name = "chown"
path = "src/chown.rs"

[dependencies]
colored = "2"
chrono  = { version = "0.4", features = ["serde"] }
