//! # SSH Service for Black Wall Core
//!
//! This module provides the init service descriptor and management wrapper
//! for OpenSSH on Black Wall Core.
//!
//! OpenSSH (`sshd`) is installed via `anx install openssh` and managed by
//! the Black Wall init daemon.
//!
//! This binary (`bwssh`) is a thin wrapper that:
//! - Generates host keys if missing
//! - Applies the Black Wall hardened sshd_config
//! - Starts sshd in foreground mode (for supervision by bwinit)

use std::path::Path;
use std::process::Command;

const SSHD_CONFIG: &str = "/etc/ssh/sshd_config";
#[allow(dead_code)]
const SSHD_KEYS_DIR: &str = "/etc/ssh";

/// Hardened sshd_config for Black Wall Core.
const SSHD_CONFIG_CONTENT: &str = r#"# Black Wall Core — hardened sshd_config
# Generated by bwssh

Port 22
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Host keys
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Authentication
LoginGraceTime 30
PermitRootLogin prohibit-password
MaxAuthTries 3
MaxSessions 10
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Security hardening
X11Forwarding no
PrintMotd yes
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server

# Logging
LogLevel VERBOSE
SyslogFacility AUTH

# Network
TCPKeepAlive yes
ClientAliveInterval 300
ClientAliveCountMax 3
"#;

/// MOTD shown after login.
const MOTD_CONTENT: &str = r#"
  ╔══════════════════════════════════════════════╗
  ║           Black Wall Core v1.0             ║
  ║   Secure by design. Powered by Rust.         ║
  ╚══════════════════════════════════════════════╝

  WARNING: Unauthorized access is prohibited.
  All sessions are logged and monitored.

"#;

fn ensure_config() {
    // Write sshd_config if missing.
    if !Path::new(SSHD_CONFIG).exists() {
        std::fs::create_dir_all("/etc/ssh").ok();
        std::fs::write(SSHD_CONFIG, SSHD_CONFIG_CONTENT).ok();
        eprintln!("[bwssh] Wrote default sshd_config");
    }

    // Write /etc/motd.
    if !Path::new("/etc/motd").exists() {
        std::fs::write("/etc/motd", MOTD_CONTENT).ok();
    }
}

fn generate_host_keys() {
    let key_types =
        [("rsa", "/etc/ssh/ssh_host_rsa_key"), ("ed25519", "/etc/ssh/ssh_host_ed25519_key")];

    for (key_type, key_path) in &key_types {
        if !Path::new(key_path).exists() {
            eprintln!("[bwssh] Generating {} host key...", key_type);
            let status = Command::new("ssh-keygen")
                .args(["-t", key_type, "-f", key_path, "-N", ""])
                .status();
            match status {
                Ok(s) if s.success() => {
                    eprintln!("[bwssh] Generated {}", key_path);
                }
                Ok(s) => {
                    eprintln!("[bwssh] ssh-keygen failed with code {:?}", s.code());
                }
                Err(e) => {
                    eprintln!("[bwssh] ssh-keygen not found: {}", e);
                }
            }
        }
    }
}

fn start_sshd() -> ! {
    eprintln!("[bwssh] Starting sshd...");
    let err = Command::new("/usr/sbin/sshd").args(["-D", "-e", "-f", SSHD_CONFIG]).exec();
    // exec() replaces the process; if we reach here, it failed.
    eprintln!("[bwssh] Failed to exec sshd: {}", err);
    std::process::exit(1);
}

fn main() {
    ensure_config();
    generate_host_keys();
    start_sshd();
}

// Required for the exec() call on Unix.
use std::os::unix::process::CommandExt;
